### ISSUE TITLE
Update from 1.0.0 -> 1.0.8 install error?

### ISSUE THREAD

**Issue by Soshaapp** [myflashlab/ANE-LAB#13]
Hi Guys :)

When I choose Download 1.0.8 and then Install, ANE LAB just closes and nothing else happens?

When I open again, it's still 1.0.0.

Please advice or should I uninstall and download the 1.0.8 manually?

Thanx :)

**Comment by myflashlab** [comment]
This might be happening probably because of permission things on your computer. anyway, you can download the installer files [.dmg](https://github.com/myflashlab/ANE-LAB/blob/master/bucket/aneLab.dmg), [.exe](https://github.com/myflashlab/ANE-LAB/blob/master/bucket/aneLab.exe) and run them. there's NO need to uninstall the software first.
