### ISSUE TITLE
[QUERY] Why is that Harman's splash screen is displayed on opening ANELAB ?

### ISSUE THREAD

**Issue by Gokulv617** [myflashlab/ANE-LAB#147]
Recent days while opening ANELAB, Harman splash screen is displayed. Why is that ? Harman is taking ANELAB too ?

**Comment by myflashlab** [comment]
Which version of the software are you using? On Mac or windows? We haven’t released an update for the software recently!

**Comment by Gokulv617** [comment]
i'm using windows version 3.20.0

![img_20210201](https://user-images.githubusercontent.com/43432782/106426602-eb8c3c00-648b-11eb-955e-eaa64d5658e6.png)

**Comment by myflashlab** [comment]
Very interesting! the current version is still using AIR SDK 32 from Adobe and we haven't released a new version since 6 months ago, it's super weird that you see Harman's logo!

Anyway, since 6 months ago we are working on a new revolutionary version for ANELAB. it may take another 2 or 3 months to be ready for release and with that version we are switching to the newer version of AIR SDK.

**Comment by Gokulv617** [comment]
"new revolutionary version of ANELAB" - sounds good to hear. Looking forward to use it

> Very interesting! the current version is still using AIR SDK 32 from Adobe and we haven't released a new version since 6 months ago, it's super weird that you see Harman's logo!
> 
> Anyway, since 6 months ago we are working on a new revolutionary version for ANELAB. it may take another 2 or 3 months to be ready for release and with that version we are switching to the newer version of AIR SDK.

**Comment by Gokulv617** [comment]
Even the ANE MAKER v10.2.2 displays Harman splash screen while opening

**Comment by myflashlab** [comment]
very interesting! but it's a no big deal as we are updating in a few months anyway :)
