### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by kxkkk** [myflashlab/ANE-LAB#42]
Hi 

We use FirebaseCore and FirebaseMessaging in our project. But Apple doesn't accept
our new app because of these anes. We are waiting for your updates.

Thanks.

Here is reject message:
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted.

**Comment by myflashlab** [comment]
The rejection reason cannot have anything to do with Firebase ANEs because they do not have any views to begin with. but maybe you are using Admob in your app? if so, that could be related to that. anyhow, we have now updated the Admob version iOS SDK and it won't be using the old UIWebview internally. which should fix the issue. If not, please let us know by emailing us through our private support channel.

**Comment by kxkkk** [comment]
We don't use Admob. We just add these ANEs:
overrideAir.ane
permissionCheck.ane
firebaseCore.ane
firebaseMessaging.ane
And we submit our mobile app to apple . We got mail from them like this: 

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

But we can publish our app if we remove firebaseCore.ane and firebaseMessaging.ane. We didn't figure out. Also our ANE version 9.0.1. We saw you updated version to 9.10.1 on github. But we can't test it because the commercial version still on v9.0.1.
